[package]
name = "lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
eyre = "0.6"
tokio = { version = "1", features = ["full"] }
alloy = { version = "0.13", features = ["full"] }
hex = "0.4"